import { Poppins } from "next/font/google";
import "./globals.css";
import Tap from "./Ui/Tap";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-poppins", // Add a CSS variable for Tailwind
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}
        bg-main
        antialiased`}
      >
        <div className="grid grid-cols-12 container mt-5">
          <div className="col-span-3 relative ">
            <Tap />
          </div>
          <div className="col-span-9 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
